#!/usr/bin/env node
// diffsnap.mjs <before.tsv> <after.tsv> — print ADDED / MODIFIED / REMOVED between two
// snapshot manifests. Generated artifacts are flagged so script-writes are distinguishable
// from source edits. (dry-run evaluation helper)
import fs from 'node:fs';

const GEN = new Set([
  'docs/frontend-workflow/_meta/workflow-state.yaml',
  'docs/frontend-workflow/_meta/screen-inventory.yaml',
]);

function load(f) {
  const m = {};
  for (const line of fs.readFileSync(f, 'utf8').trim().split(/\r?\n/).filter(Boolean)) {
    const [p, h] = line.split('\t');
    m[p] = h;
  }
  return m;
}

const before = load(process.argv[2]);
const after = load(process.argv[3]);

const added = [];
const modified = [];
const removed = [];
for (const p of Object.keys(after)) {
  if (!(p in before)) added.push(p);
  else if (before[p] !== after[p]) modified.push(p);
}
for (const p of Object.keys(before)) if (!(p in after)) removed.push(p);

const tag = (p) => (GEN.has(p) ? '  [generated by workflow:state]' : '');
console.log('ADDED:');
if (added.length) added.sort().forEach((p) => console.log('  + ' + p)); else console.log('  (none)');
console.log('MODIFIED:');
if (modified.length) modified.sort().forEach((p) => console.log('  ~ ' + p + tag(p))); else console.log('  (none)');
console.log('REMOVED:');
if (removed.length) removed.sort().forEach((p) => console.log('  - ' + p)); else console.log('  (none)');

// machine-readable summary line for downstream asserts
const srcChanges = [...added, ...modified].filter((p) => p.startsWith('src/'));
const nonGenDocChanges = [...added, ...modified].filter((p) => !p.startsWith('src/') && !GEN.has(p));
console.log('\nSUMMARY ' + JSON.stringify({
  added: added.length,
  modified: modified.length,
  removed: removed.length,
  srcChanges,
  nonGenDocChanges,
}));
